global:
  node: "hawk-d12"
  sync_regime: "slave"
settings:
  poll_timeout_ms: 1000
  sys_metric_update_freq: 5 # каждый пятый раз после сборка метрик
  log_level: "debug"
temperature:
  sensors:
    - name: "coretemp"
network:
  interface_name: "eth1"
zmq:
  endpoint: "tcp://armsrv:10000"
  queue_size: 10000
  timeout_after_close_ms: 1000
services:
  ptp4l:
    on: true
    source: "journal"
    dev: "eth1"
  phc2sys:
    on: true
    source: "journal"
    dev: "eth1"
  ppswatch:
    on: true
    source: "subproccess"
    dev: "/dev/pps2"