[global]
network_transport       L2
delay_mechanism         E2E

clock_servo             pi

time_stamping           hardware

priority1               128
priority2               128
clockClass              248

logAnnounceInterval     1
announceReceiptTimeout  3
logSyncInterval         -1
logMinDelayReqInterval  -1

delay_filter            moving_median
delay_filter_length     20

logging_level           6

domainNumber            0

[rteth0]