global:
  node: "hawk-d12"
settings:
  poll_timeout_ms: 10000
  sys_metric_update_freq: 15
  log_level: "debug"
temperature:
  sensors:
    - name: "coretemp"
zmq:
  endpoint: "tcp://armsrv:10000"
  queue_size: 10000
  timeout_after_close_ms: 1000
services:
  ptp4l:
    on: true
    source: "journal"
    dev: "rteth0"
  phc2sys:
    on: true
    source: "journal"
    dev: "rteth0"
  ppswatch:
    on: true
    source: "subproccess"
    dev: "/dev/pps2"