[global]
network_transport       L2
delay_mechanism         auto

time_stamping           hardware

clock_servo             pi

priority1               128
priority2               128
clockClass              248

logAnnounceInterval     1
announceReceiptTimeout  3
logSyncInterval         -1
logMinDelayReqInterval  -1

delay_filter            moving_median
delay_filter_length     10

logging_level           6

domainNumber            0

[eth1]